// <auto-generated />
using Actividad4Prog3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actividad4Prog3.Migrations
{
    [DbContext(typeof(Actividades4Context))]
    [Migration("20250711231154_CrearTablaEstudiantesBien")]
    partial class CrearTablaEstudiantesBien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Actividad4Prog3.Models.Calificacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoMateria")
                        .HasColumnType("int");

                    b.Property<string>("MatriculaEstudiante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Nota")
                        .HasColumnType("float");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Califica__3214EC07F4F667FC");

                    b.HasIndex("CodigoMateria");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Actividad4Prog3.Models.Estudiante", b =>
                {
                    b.Property<string>("Matricula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TerminosYCondiciones")
                        .HasColumnType("bit");

                    b.Property<string>("TipoIngreso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Matricula");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Actividad4Prog3.Models.Materia", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo")
                        .HasName("PK__Materias__06370DAD199ED2F2");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("Actividad4Prog3.Models.Calificacione", b =>
                {
                    b.HasOne("Actividad4Prog3.Models.Materia", "CodigoMateriaNavigation")
                        .WithMany("Calificaciones")
                        .HasForeignKey("CodigoMateria")
                        .IsRequired()
                        .HasConstraintName("FK__Calificac__Codig__3D5E1FD2");

                    b.Navigation("CodigoMateriaNavigation");
                });

            modelBuilder.Entity("Actividad4Prog3.Models.Materia", b =>
                {
                    b.Navigation("Calificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
